name: Tests Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
    
    - name: Run flake8 (suo)
      uses: julianwachholz/flake8-action@v2
      with:
        checkName: 'flake8_py3'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  tests_3_6:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
      env:
        POETRY_VIRTUALENVS_CREATE: false
        ENV: ci
    - name: Test with pytest
      run: |
        pytest tests/

  tests_3_7:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
      env:
        POETRY_VIRTUALENVS_CREATE: false
        ENV: ci
    - name: Test with pytest
      run: |
        pytest tests/

  tests_3_8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
      env:
        POETRY_VIRTUALENVS_CREATE: false
        ENV: ci
    - name: Test with pytest
      run: |
        pytest tests/

  tests_3_9:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
      env:
        POETRY_VIRTUALENVS_CREATE: false
        ENV: ci
    - name: Test with pytest
      run: |
        pytest tests/
